# paths #
# database related paths
database_path: /data/journe_core/journe_core.db
dummy_db_json_path: /data/dummy_db.json
# sql command paths
data_structure_sql_path: /src/data/journe_data_structure.sql
# puts
task_payload_sql_path: /src/data/journe_payload_task.sql
pot_payload_sql_path: /src/data/journe_payload_pot.sql
# read - all
read_tasks: /src/data/journe_read_tasks.sql
read_pots: /src/data/journe_read_pots.sql
# get - on ID or name
get_task_sql_path: /src/data/journe_get_task.sql
get_pot_sql_path: /src/data/journe_get_pot.sql
# removes
remove_task_sql_path: /src/data/journe_remove_task.sql
remove_pot_sql_path: /src/data/journe_remove_pot.sql
# updates
update_task: /src/data/journe_update_task.sql
update_pot: /src/data/journe_update_pot.sql
